#!/usr/bin/env sh

[ -z "$IMAGE" ] && IMAGE=ghcr.io/dasimmet/pyinstaller-cross:latest
docker run --rm $DOCKER_ARGS -v "$PWD:/runtime/workdir" -e TARGET -- "$IMAGE" /usr/local/bin/pyinstaller-cross "$@"